# Generated by Django 5.2.7 on 2025-10-17 02:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_ref', models.UUIDField(db_index=True)),
                ('need_ref', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('request_type', models.CharField(choices=[('ECON', 'Económica'), ('MAT', 'Materiales'), ('MO', 'Mano de obra'), ('OTRO', 'Otro')], max_length=10)),
                ('target_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('reserved_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fulfilled_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('OPEN', 'Pendiente'), ('RESERVED', 'Reservada'), ('COMPLETED', 'Completada')], db_index=True, default='OPEN', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project_ref'], name='cloudapi_co_project_bc9a44_idx'), models.Index(fields=['need_ref'], name='cloudapi_co_need_re_cc5ce2_idx'), models.Index(fields=['status'], name='cloudapi_co_status_11689c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('reserved_qty__gte', 0)), name='req_reserved_nonneg'), models.CheckConstraint(condition=models.Q(('fulfilled_qty__gte', 0)), name='req_fulfilled_nonneg'), models.CheckConstraint(condition=models.Q(('target_qty__isnull', True), ('fulfilled_qty__lte', models.F('target_qty')), _connector='OR'), name='req_fulfilled_lte_target_if_set'), models.CheckConstraint(condition=models.Q(('target_qty__isnull', True), ('reserved_qty__lte', models.F('target_qty')), _connector='OR'), name='req_reserved_lte_target_if_set')],
            },
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_label', models.CharField(blank=True, db_index=True, max_length=140, null=True)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('ACTIVE', 'Comprometido'), ('FULFILLED', 'Completado'), ('CANCELLED', 'Cancelado')], db_index=True, default='ACTIVE', max_length=12)),
                ('commitment_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='cloudapi.collaborationrequest')),
            ],
            options={
                'ordering': ['-commitment_date'],
                'indexes': [models.Index(fields=['request', 'status'], name='cloudapi_co_request_52027a_idx')],
            },
        ),
    ]
