# Generated by Django 5.2.7 on 2025-11-11 01:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_by_ong', models.CharField(blank=True, max_length=200)),
                ('bonita_case_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observer_label', models.CharField(help_text='Nombre del Consejo o supervisor', max_length=150)),
                ('text', models.TextField(help_text='Descripción de la observación o mejora')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='cloudapi.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('request_type', models.CharField(choices=[('ECON', 'Económica'), ('MAT', 'Materiales'), ('MO', 'Mano de obra'), ('OTRO', 'Otro')], max_length=10)),
                ('target_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('reserved_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fulfilled_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('OPEN', 'Pendiente'), ('RESERVED', 'Reservada'), ('COMPLETED', 'Completada')], db_index=True, default='OPEN', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='cloudapi.project')),
            ],
            options={
                'db_table': 'collaboration_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='cloudapi.project')),
            ],
            options={
                'ordering': ['start_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, db_index=True, max_length=140, null=True)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('ACTIVE', 'Comprometido'), ('FULFILLED', 'Completado'), ('CANCELLED', 'Cancelado')], db_index=True, default='ACTIVE', max_length=12)),
                ('commitment_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='cloudapi.collaborationrequest')),
            ],
            options={
                'db_table': 'commitment',
                'ordering': ['-commitment_date'],
                'indexes': [models.Index(fields=['request', 'status'], name='commitment_request_591fab_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='collaborationrequest',
            index=models.Index(fields=['project'], name='collaborati_project_e0f4f1_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborationrequest',
            index=models.Index(fields=['status'], name='collaborati_status_d4c635_idx'),
        ),
        migrations.AddConstraint(
            model_name='collaborationrequest',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_qty__gte', 0)), name='req_reserved_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='collaborationrequest',
            constraint=models.CheckConstraint(condition=models.Q(('fulfilled_qty__gte', 0)), name='req_fulfilled_nonneg'),
        ),
    ]
