# Generated by Django 5.2.7 on 2025-10-17 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloudapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='collaborationrequest',
            new_name='collaborati_project_83a173_idx',
            old_name='cloudapi_co_project_bc9a44_idx',
        ),
        migrations.RenameIndex(
            model_name='collaborationrequest',
            new_name='collaborati_need_re_4dda0d_idx',
            old_name='cloudapi_co_need_re_cc5ce2_idx',
        ),
        migrations.RenameIndex(
            model_name='collaborationrequest',
            new_name='collaborati_status_d4c635_idx',
            old_name='cloudapi_co_status_11689c_idx',
        ),
        migrations.RenameIndex(
            model_name='commitment',
            new_name='commitment_request_591fab_idx',
            old_name='cloudapi_co_request_52027a_idx',
        ),
        migrations.AlterModelTable(
            name='collaborationrequest',
            table='collaboration_request',
        ),
        migrations.AlterModelTable(
            name='commitment',
            table='commitment',
        ),
    ]
