# Generated by Django 5.2.7 on 2025-11-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='project',
        ),
        migrations.AlterField(
            model_name='collaborationrequest',
            name='project',
            field=models.PositiveIntegerField(db_index=True, help_text='ID del proyecto en el sistema ProjectPlanning (Django web).'),
        ),
        migrations.RemoveField(
            model_name='stage',
            name='project',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameIndex(
            model_name='collaborationrequest',
            new_name='collaborati_project_c60c3f_idx',
            old_name='collaborati_project_e0f4f1_idx',
        ),
        migrations.AddField(
            model_name='commitment',
            name='ong_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Observation',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
    ]
