# Generated by Django 5.2.7 on 2025-11-24 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloudapi', '0002_remove_observation_project_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='collaborationrequest',
            name='req_reserved_nonneg',
        ),
        migrations.RemoveConstraint(
            model_name='collaborationrequest',
            name='req_fulfilled_nonneg',
        ),
        migrations.RemoveField(
            model_name='collaborationrequest',
            name='fulfilled_qty',
        ),
        migrations.RemoveField(
            model_name='collaborationrequest',
            name='reserved_qty',
        ),
    ]
