# Generated by Django 5.2.7 on 2025-10-17 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloudapi', '0002_rename_cloudapi_co_project_bc9a44_idx_collaborati_project_83a173_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborationrequest',
            name='unit',
        ),
    ]
