# Generated by Django 5.2.7 on 2025-11-26 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloudapi', '0003_remove_collaborationrequest_req_reserved_nonneg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commitment',
            name='amount',
        ),
    ]
