# Generated by Django 5.2.7 on 2025-11-06 22:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudapi', '0003_remove_collaborationrequest_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_ref', models.UUIDField(db_index=True, help_text='UUID del Proyecto en Bonita/App')),
                ('observer_label', models.CharField(help_text='Nombre del Consejo o supervisor', max_length=150)),
                ('text', models.TextField(help_text='Descripción de la observación o mejora')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_ref', models.UUIDField(db_index=True, help_text='UUID del Proyecto en Bonita/App')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
